# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

before_script:
  - R CMD build --no-build-vignettes

dist: trusty
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
osx_image: xcode10
language: R
r:
  - oldrel
  - release
  - devel
sudo: false
cache: packages



