# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

dist: trusty
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
osx_image: xcode10
language: R
r:
  - oldrel
  - devel
  - release
sudo: false
cache: packages
