---
title: "NEWS"
author: "Fabian Dvorak"
date: "March 31 2025"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# stratEst 1.1.7
* fixes NOTE triggered by configure.ac

# stratEst 1.1.6
* fixes bug if input.lag is vector

# stratEst 1.1.5
* fixes bug if input is NA in later periods

# stratEst 1.1.4
* uses TRUE and FALSE instead of T and F
* adds \value to .Rd files
* calls on.exit() to reset settings

# stratEst 1.1.3
* next try to fix UBSAN errors

# stratEst 1.1.2
* fix remaining UBSAN problems of version 1.1.0

# stratEst 1.1.1
* fixes UBSAN problems of version 1.1.0

# stratEst 1.1.0
* introduces a plot method for strategies and shares
* fixes bug in the computation of bootstrapped standard errors
* correct minor errors in documentation
* removes the outdated check_cluster_id function

# stratEst 1.0.1
* fixes clang-UBSAN and gcc UBSAN errors
* makes sure RcppArmadillo package version >= 0.9.900.0.0 is installed
* fixes bug in function stratEst.simulate()
* corrects the number of free parameters returned by stratEst.model()
* corrects object returned by stratEst.model()

# stratEst 1.0.0
## Classes
* introduces the S3 class stratEst.model
* introduces the S3 class stratEst.data
* introduces the S3 class stratEst.strategy
* introduces the S3 class stratEst.check

## Functions
* new function stratEst.data() to reshape data
* new function stratEst.simulate() to simulate data
* new function stratEst.model() to fit models
* new function stratEst.strategy() to generate strategies
* new function stratEst.check() to check fitted models
* new function stratEst.test() to test estimated model parameters
* function stratEst() is deprecated

## New features
* introduces the option to estimate models with samples specific parameters
* introduces a Firth penalty option for models with covariates
* introduces the option to fix trembles and coefficients

## Bug fixes 
* fixes bug in the estimation of models with covariates and more than two strategies
* fixes bug for unsorted data

# stratEst 0.1.2

* fixes a bug in the calculation of the score function for trembles
* fixes a bug in the selection procedure if the input object strategies is an integer
* contains the current working paper version


# stratEst 0.1.1

* fixes the overload ambiguity of the log() function in C++ code
* reports solutions with tremble parameters bigger than 0.5

# stratEst 0.1.0

* first release
