# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' The stratEst function
#'
#' @param data The data matrix.
#' @export
stratEst_cpp <- function(data, strategies, shares, covariates, cluster, response = "mixed", r_responses = "no", r_trembles = "global", select = "no", crit = "BIC", SE = "yes", outer_runs = 10L, outer_tol_eval = 0, outer_max_eval = 1000L, inner_runs = 100L, inner_tol_eval = 0, inner_max_eval = 100L, LCR_runs = 100L, LCR_tol_eval = 0L, LCR_max_eval = 1000L, BS_samples = 1000L, newton_stepsize = 1L, penalty = 0) {
    .Call('_stratEst_stratEst_cpp', PACKAGE = 'stratEst', data, strategies, shares, covariates, cluster, response, r_responses, r_trembles, select, crit, SE, outer_runs, outer_tol_eval, outer_max_eval, inner_runs, inner_tol_eval, inner_max_eval, LCR_runs, LCR_tol_eval, LCR_max_eval, BS_samples, newton_stepsize, penalty)
}

